server {
    listen 80;
    server_name streltsov-developer.ru www.streltsov-developer.ru;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

#     location / {
#         try_files $uri $uri/ /index.html;
#     }

    location / {
        return 301 https://$host$request_uri;
    }

    location ~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name streltsov-developer.ru www.streltsov-developer.ru;
    root /usr/share/nginx/html;

    ssl_certificate /etc/letsencrypt/live/streltsov-developer.ru/fullchain1.pem;
    ssl_certificate_key /etc/letsencrypt/live/streltsov-developer.ru/privkey1.pem;

    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}